<a href="https://colab.research.google.com/github/Tasneem3614/MSC_FDS_506/blob/main/fds%20prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)


(3,)


In [6]:
print(a[0],a[1],a[2])

1 2 3


In [8]:
b=np.array([[1,2],[3,4]])

In [9]:
b


array([[1, 2],
       [3, 4]])

In [10]:
print(b.shape)

(2, 2)


In [11]:
print(b[0,0],b[0,1],b[1,1])

1 2 4


In [12]:
c=np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

print(c[0,1],c[1,0],c[2,0],c[2,1])
